#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# Coturn TURN Server Setup for bitresearch Cross-Network WebRTC
# ═══════════════════════════════════════════════════════════════
#
# This script installs and configures a Coturn TURN server
# to enable WebRTC peer connections across different networks
# (behind NATs, firewalls, etc).
#
# Usage:
#   chmod +x scripts/setup-turn.sh
#   sudo ./scripts/setup-turn.sh [--secret YOUR_SECRET] [--realm YOUR_REALM]
#
# Environment variables (override defaults):
#   TURN_SECRET   - Shared secret for HMAC credential generation (required for production)
#   TURN_REALM    - Realm for the TURN server (default: bitresearch.training)
#   TURN_PORT     - TURN port (default: 3478)
#   TURN_TLS_PORT - TURN TLS port (default: 5349)
#   EXTERNAL_IP   - Public IP (auto-detected if not set)
#
# After setup:
#   1. Start coturn:  sudo systemctl start coturn
#   2. Start bitresearch signaling with env vars:
#      TURN_SECRET=<secret> TURN_HOST=<public-ip> pnpm run dev:signaling
#
# The signaling server will auto-generate time-limited HMAC
# credentials and distribute them to peers on ring formation.
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

# ── Parse args ──
TURN_SECRET="${TURN_SECRET:-$(openssl rand -hex 32)}"
TURN_REALM="${TURN_REALM:-bitresearch.training}"
TURN_PORT="${TURN_PORT:-3478}"
TURN_TLS_PORT="${TURN_TLS_PORT:-5349}"

while [[ $# -gt 0 ]]; do
  case $1 in
    --secret) TURN_SECRET="$2"; shift 2 ;;
    --realm) TURN_REALM="$2"; shift 2 ;;
    --port) TURN_PORT="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ── Detect public IP ──
if [ -z "${EXTERNAL_IP:-}" ]; then
  EXTERNAL_IP=$(curl -s https://api.ipify.org || curl -s https://ifconfig.me || echo "")
  if [ -z "$EXTERNAL_IP" ]; then
    echo "❌ Could not detect public IP. Set EXTERNAL_IP env var."
    exit 1
  fi
fi

echo "╔════════════════════════════════════════════════════════════╗"
echo "║       🌐 bitresearch TURN Server Setup                   ║"
echo "╠════════════════════════════════════════════════════════════╣"
echo "║  Realm:       $TURN_REALM"
echo "║  TURN Port:   $TURN_PORT"
echo "║  TLS Port:    $TURN_TLS_PORT"
echo "║  External IP: $EXTERNAL_IP"
echo "║  Secret:      ${TURN_SECRET:0:8}..."
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# ── Install Coturn ──
echo "📦 Installing coturn..."
if command -v apt-get &>/dev/null; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq coturn
elif command -v dnf &>/dev/null; then
  sudo dnf install -y coturn
elif command -v brew &>/dev/null; then
  brew install coturn
else
  echo "❌ Unsupported package manager. Install coturn manually."
  exit 1
fi

# ── Configure Coturn ──
echo "⚙️  Writing /etc/turnserver.conf..."
sudo tee /etc/turnserver.conf > /dev/null << EOF
# bitresearch TURN Server Configuration
# Generated by setup-turn.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ── Network ──
listening-port=$TURN_PORT
tls-listening-port=$TURN_TLS_PORT
# Listen on all interfaces
listening-ip=0.0.0.0
relay-ip=0.0.0.0
external-ip=$EXTERNAL_IP

# ── Authentication ──
# Use the long-term HMAC credential mechanism (RFC 5389)
# The signaling server generates time-limited credentials using this secret
use-auth-secret
static-auth-secret=$TURN_SECRET
realm=$TURN_REALM

# ── Security ──
# Reject allocations from/to private IPs (prevents relay abuse)
no-multicast-peers
denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=100.64.0.0-100.127.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.0.0.0-192.0.0.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=224.0.0.0-255.255.255.255

# ── Performance ──
# Fingerprints for STUN message integrity
fingerprint
# Total relay allocation limit
total-quota=100
# Per-user relay limit
user-quota=12
# Max bytes/second per session (10 MB/s — plenty for gradient data)
max-bps=10485760

# ── Logging ──
log-file=/var/log/turnserver.log
simple-log
# Verbose for debugging (comment out in production)
# verbose

# ── Misc ──
# Process as daemon
# daemon  # systemd handles this
no-stdout-log
EOF

# ── Enable and start ──
echo "🚀 Enabling coturn service..."

# Ensure coturn is allowed to start (Debian/Ubuntu default blocks it)
if [ -f /etc/default/coturn ]; then
  sudo sed -i 's/^#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn
fi

sudo systemctl enable coturn
sudo systemctl restart coturn

# ── Verify ──
echo ""
echo "🔍 Verifying TURN server..."
sleep 2

if systemctl is-active --quiet coturn; then
  echo "✅ Coturn is running!"
else
  echo "❌ Coturn failed to start. Check: sudo journalctl -u coturn -n 50"
  exit 1
fi

# ── Firewall rules ──
echo ""
echo "🔥 Opening firewall ports..."
if command -v ufw &>/dev/null; then
  sudo ufw allow $TURN_PORT/tcp
  sudo ufw allow $TURN_PORT/udp
  sudo ufw allow $TURN_TLS_PORT/tcp
  sudo ufw allow $TURN_TLS_PORT/udp
  # Relay port range
  sudo ufw allow 49152:65535/udp
  echo "✅ UFW rules added"
elif command -v firewall-cmd &>/dev/null; then
  sudo firewall-cmd --permanent --add-port=$TURN_PORT/tcp
  sudo firewall-cmd --permanent --add-port=$TURN_PORT/udp
  sudo firewall-cmd --permanent --add-port=$TURN_TLS_PORT/tcp
  sudo firewall-cmd --permanent --add-port=$TURN_TLS_PORT/udp
  sudo firewall-cmd --permanent --add-port=49152-65535/udp
  sudo firewall-cmd --reload
  echo "✅ Firewalld rules added"
else
  echo "⚠️  No firewall tool detected. Manually open ports: $TURN_PORT, $TURN_TLS_PORT (tcp+udp), 49152-65535 (udp)"
fi

# ── Print env vars for signaling server ──
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║  ✅ TURN Server Ready!                                   ║"
echo "╠════════════════════════════════════════════════════════════╣"
echo "║                                                          ║"
echo "║  To use with bitresearch, start the signaling server     ║"
echo "║  with these environment variables:                       ║"
echo "║                                                          ║"
echo "║  export TURN_SECRET='$TURN_SECRET'"
echo "║  export TURN_HOST='$EXTERNAL_IP'"
echo "║  export TURN_PORT='$TURN_PORT'"
echo "║  export TURN_REALM='$TURN_REALM'"
echo "║  pnpm run dev:signaling                                  ║"
echo "║                                                          ║"
echo "║  The signaling server will auto-generate HMAC            ║"
echo "║  credentials for each peer (24h TTL).                    ║"
echo "║                                                          ║"
echo "║  Test TURN connectivity:                                 ║"
echo "║  curl http://localhost:8788/turn-credentials              ║"
echo "╚════════════════════════════════════════════════════════════╝"

# Save env vars for convenience
ENV_FILE="$(dirname "$0")/../.env.turn"
cat > "$ENV_FILE" << EOF
# TURN Server Configuration (generated by setup-turn.sh)
TURN_SECRET=$TURN_SECRET
TURN_HOST=$EXTERNAL_IP
TURN_PORT=$TURN_PORT
TURN_REALM=$TURN_REALM
EOF
echo ""
echo "💾 Saved to $ENV_FILE"
echo "   Load with: source $ENV_FILE"
